//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int Id_Link { get; set; }
        public int Id_Subject { get; set; }
        public string Pdf_Name { get; set; }
        public string Link1 { get; set; }
        public Nullable<int> Id_Category { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Category Category { get; set; }
    }
}
