//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoClick
    {
        public int DBReturnNo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
